### PR TITLE
fix images with no alt text

### PR DESCRIPTION
**Pull request by kfang**
fixes sirthias/pegdown#114

### CODE REVIEW

**Comment by sirthias** [comment]
Thanks for this patch!
Are we missing a test that should have been red before and is now green?

**Comment by kfang** [comment]
Just looking into it now but it looks like there isn't a test with an empty alt?

**Comment by kfang** [comment]
Also, it looks like the recent merge of 1bffa457ed20177c5d766109b4c469831bbb2282 broke some tests so I'll try to get those sorted out.

**Comment by vsch** [comment]
All Tests passed when I ran them. Sometimes the first run of `sbt test` after source changes would report failed tests, however these would disappear when `sbt test` was invoked a second time.

**Comment by kfang** [comment]
thanks @vsch, I meant that the tests are broken on my branch :)  Your fixes look good.

**Comment by kfang** [comment]
@sirthias not sure if there's a more clever way of fixing this. Lemme know if you have any better thoughts. Also added an empty image alt test.

**Comment by sirthias** [comment]
Thanks! Looks good!

**Pull request merged**
