### PR TITLE
Updated taglist

### PR DESCRIPTION
**Pull request by Deraen**
Replaces PR #164 

I sorted the tag lists and added a test to check few tags. AST test is used as HTML tests are passed through jTidy which doesn't accept HTML5 tags.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Maybe it makes sense to sort this programmatically as it would allow easier parsing by people reading the code if some hierarchy is maintained?

**Comment by Deraen** [comment]
Using hashset instead of sorted array and binary search should make sense.

**Comment by Deraen** [comment]
Okay, I reverted the order and used HashSet instead so the check should be fast still.

Friend mentioned using Enum might be good idea, with try/catch and valueOf it should be as fast to check if enum contains the string.

**Comment by Deraen** [comment]
I'm thinking hashset is the most reasonable solution for this.

**Comment by martinklepsch** [comment]
:+1:

**Comment by martinklepsch** [comment]
@sirthias ping :relaxed:

**Comment by podviaznikov** [comment]
+1 on this

**Comment by martinklepsch** [comment]
@sirthias please? :pray:

**Comment by sirthias** [comment]
Great. Thanks for this patch!

**Comment by martinklepsch** [comment]
@sirthias could we get a new release as well please? :)

**Comment by sirthias** [comment]
@vsch is still hammering away at a bunch of other issues and improvements.
I'll publish a new release once he is done with his current spree of pegdown patches...

**Comment by martinklepsch** [comment]
@sirthias any chance you can give an update on when this will get released? :)

**Comment by vsch** [comment]
If you desperately need a new pegdown you can use the unofficial version from my vsc/idea-multimarkdown project in the lib section, which has all the PR's that were merged so far and the latest PR that is still pending. The build number is not official either, I increment it so I can keep track of changed versions for the plugin. However, if you need the update and can't wait it will solve your problem: https://github.com/vsch/idea-multimarkdown/blob/master/lib/pegdown-1.5.14.jar?raw=true

@sirthias is probably too busy these days and I can sympathize with him.

**Comment by vsch** [comment]
Forgot to mention that the source for the unofficial pedown jar is available from my fork: https://github.com/vsch/pegdown. It also has the updated readme for the new extensions.

**Pull request merged**
