### PR TITLE
Fixed bug with Extensions

### PR DESCRIPTION
**Pull request by tcreswick**
This fixes the bug identified here https://github.com/sirthias/pegdown/issues/161

### CODE REVIEW

**Comment by Kevin-Lee** [comment]
Fixes #159 as well.

**Comment by sirthias** [comment]
Thanks, guys!

**Comment by tcreswick** [comment]
Great. What's the schedule for the next release (Maven)?

**Comment by sirthias** [comment]
Nothing scheduled so far.

**Comment by Kevin-Lee** [comment]
Oops, wrong link. #160 has nothing to do with this PR.

**Pull request merged**
