### PR TITLE
fixed tables not allowing cells containing a single '-' character

### PR DESCRIPTION
**Pull request by Jcurrie314**

### CODE REVIEW

**Comment by Deraen** [comment]
It is hard to see the real change as you have removed loads of trailing whitespaces. I agree that trailing whitespaces should be removed, but I think it should be done in different commit so that it would be easier to see the changes.

**Comment by sirthias** [comment]
Is this problem already fixed in the current master branch?
Unfortunately your patch doesn't contain a new test, which I could extract and run to check.

**Comment by vsch** [comment]
@sirthias, I merged this fix in my first PR but without the white space changes. I tried a table with single - for header/body separator row and it does work.

**Comment by sirthias** [comment]
Cool, thanks for confirming! (I'm in the process of releasing 1.6.0 with all your patches...)

**Pull request closed without merging**
